app:
  name: go-fitbyte

server:
  port: 3000
  host: "localhost"
  prefork: false

# database:
#   username: "abc"
#   password: "password"
#   name: "db-fitbyte-dev"
#   host: "db"
#   ports: 5432
#   maxConnections: 10

database:
  username: "postgres"
  password: "rootpass"
  name: "mydb"
  host: "localhost"
  ports: 5432
  maxConnections: 10

swagger:
  title: "Go-FitByte API Documentation"
  path: "swagger"
  base_path: "/"
  file_path: "./docs/swagger.json"
  cache_age: 86400
